yolact_ros2_node:
  ros__parameters:
    yolact_path: /home/ros/semantic-mapping/src/yolact
    model_path:  /home/ros/semantic-mapping/src/yolact/weights/yolact_plus_resnet50_54_800000.pth
    image_topic: /color/image_raw
    use_compressed_image: False
    publish_visualization: True
    publish_detections: True
    display_visualization: True
    display_masks: True
    display_bboxes: True
    display_text: True
    display_scores: True
    display_fps: True
    score_threshold: 0.0
    crop_masks: True
    top_k: 5
    publish_namespace: /yolact_ros2
